
COMPILER = g++
PROGRAM_NAME = chip8_emulator.run
TARGET_FILE = main.cpp
COMPILER_FLAGS = -std=c++1z -w
EXTRA_CLASSES = chip8.cpp
LIBRARY_FLAGS = -lSDL2
DEBUG_FLAGS = -g

all: 
	$(COMPILER) $(TARGET_FILE) $(COMPILER_FLAGS) $(LIBRARY_FLAGS) $(EXTRA_CLASSES) -o $(PROGRAM_NAME)
debug:
	$(COMPILER) $(DEBUG_FLAGS) $(TARGET_FILE) $(COMPILER_FLAGS) $(LIBRARY_FLAGS) $(EXTRA_CLASSES) -o debug.out	
clear:
	rm $(PROGRAM_NAME) 
